README.md, doc/packer.txt, lua/packer.lua, lua/packer/plugin_utils.lua
Adds the `as` keyword to allow plugins to be installed under aliases. Closes #28
=> Add plugin alias feature to close #28

README.md, doc/packer.txt, lua/packer.lua, lua/packer/clean.lua, lua/packer/install.lua, lua/packer/plugin_types/local.lua, lua/packer/plugin_utils.lua, lua/packer/util.lua
Fixed the problems mentioned in #43 .
> When used as control expression, the only false values in Lua are false and nil , everything else is evaluated as true value
This means that the following if statement is always true, because `vim.fn.executable` returns a number
```lua
vim.fn.executable('ln')
```
In Windows 10 you need to have developer mode enabled to use local plugins. This should probably be mentioned in the README.
I don't know where to put this, so could you please do this?
`mklink` has the `from` and `to` swapped.
It looks like your job lib is using powershell and not cmd. This means that you have to use `cmd /C mklink ...` instead of `mklink ...`
Don't think I need to explain this. You just forgot the `/d` flag of `mklink`.
=> fix: windows related bugs

lua/packer/compile.lua
If user has a shared configuration for nvim and vim this feature guard
will check if the user is on nvim if they are not then it will just
`finish` sourcing the file.
Users might want to have the same configuration for both neovim and vim.
If for some reason they are on vim instead of nvim their configuration
will gracefully degrate intead of throwing errors.
As the compiled file vimscript file is in the users runtime it should
degrade gracefully.
Fix: #65
=> feat(compile): Feature guard around nvim

README.md
* Clarify that "stable" Neovim v0.4.4 is not supported by Packer
* Demonstrate the use of `autocmd` to run `PackerCompile` whenever the plugin script is updated
=> Readme updates: clarify that v0.4.4 is too old, mention autocmd PackerCompile

lua/packer/display.lua
removes the `vim.inspect()` wrapping the installation error message and splits the message by newline for correct display
=> Fix: tidy display of installation errors. Fixes #73

lua/packer.lua
Fixes #52. @gagbo confirms that this changed command works for old `git` versions. However, the output appears to be slightly different on detached HEAD repos, i.e. if we have a specific commit checked out - this version prints `HEAD`, whereas `git branch --show-current` prints nothing.
I need to try to check if that difference will break anything (basically, I need to review the `git` logic and make sure we're not expecting an empty string anywhere); then this can be merged.
=> Use command for current branch compatible with old git versions

lua/packer/plugin_types/git.lua
Copy the entire environment before assigning `GIT_TERMINAL_PROMPT`
=> Fix #100: copy existing environment variable values

lua/packer/compile.lua
When using older versions of Neovim alongside `packer`, `has('nvim')` isn't quite restrictive enough. We need to know for sure if we have 0.5.
=> Test for Neovim 0.5 on packer_compiled

lua/packer.lua, lua/packer/display.lua
Following up on #106: the idea is to be able to run PackerSync and have
it cleanup stale plugins without asking for input (imagine the user is
in --headless mode).
Originally, I had a no_input parameter, but based on feedback I updated
the code to have a config parameter that modifies the behavior of the
display module.
=> display: add a non_interactive config parameter

README.md, doc/packer.txt, lua/packer.lua
currently `config.disable_commands` only work with `require'packer'.startup()` which seems like an arbitrary limitation.
=> init: make config.disable_commands work also with require'packer'.init()

lua/packer/plugin_utils.lua
Handle changes to `math.max` (I think...) in new LuaJIT without breaking old versions by checking for an empty table before using `math.max(unpack(...))`
=> Fix #103: Check for a non-empty table before using math.max(unpack(...))

lua/packer/util.lua
As you can see in the screenshot, the current floating window looks broken. So, I changed the highlights, dimensions, and added borders to make it look nice. Need feedback on how it looks on different themes.
Before:
After:
Thoughts? @wbthomason
=> remove `bg_buf` and `bg_win` from floating window

doc/packer.txt, lua/packer/display.lua
This PR implements the changes described in #35.
- `packer` now displays available keybindings in the results window
- these keybindings are documented in `:help`
Let me know if you have any comments about style or if I should make other changes.
=> Document display window keybindings

README.md, doc/packer.txt, lua/packer.lua, lua/packer/display.lua
Closes #34
This PR makes the keybindings of the display window configurable via `config.display.keybindings`
A few notes/questions:
- There is no validation process for the keybindings, users can input invalid mappings
- Should there be an option to disable the keybindings altogether?
- I can delete `keymap_display_order` if you think it makes the the code harder to read for no real benefit
=> Make results window keybindings configurable

lua/packer/compile.lua
Fixes #115
Just a small additional check for the value of `vim.v.count`, otherwise it's always truthy
=> Fix jump on operator lazy-loading

lua/packer/display.lua
Prevents the error:
```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/packer.nvim/lua/packer/display.lua:157: Expected 4 arguments
```
Which is caused when passing `id=nil` into `nvim_buf_get_extmark_by_id`. I think this happens when an update finishes quickly as it causes `self.marks[plugin] = nil` to be called. Not really sure though.
Btw this happens on a plugin repo which I had modified with local commits and pushed to a fork, not sure why that would matter though.
=> Fix update error

lua/packer.lua
This is in reference to #140. Before, the `as` name was not used preferentially to the repo name provided in the specification. This will make the `as` alias be used instead, if present.
Closes #140
=> Use aliased name as plugin name if present

README.md, lua/packer.lua, lua/packer/clean.lua, lua/packer/display.lua, lua/packer/plugin_utils.lua, lua/packer/update.lua
This is a followup to #143. It uses a more consistent method for checking the type of a directory than attempting to embed it into the `packer_compile`.
The following changes have been made:
* `plugin_utils.find_missing_plugins` now uses two metrics to determine whether or not a plugin is "missing":
1. The plugin is not installed at all (directory is missing).
2. The plugin is installed, but the `guess_dir_type` does not match `plugin.type`.
* `PackerClean` has been re-implemented in terms of `find_missing_plugins`. This is because some missing plugins are also plugins which need to be cleaned before a reinstall (i.e. moving from local to upstream and vice versa).
* See the commit message for 51bf0962d450eebe7d123a41279810ee1724406c. Essentially it just uses more logic from other parts of …
=> Check dir type for changes

lua/packer/compile.lua
This is still not working 100%. While the created mapping in the compiled script does not throw an error anymore and successfully loads the packages, the feedkeys do not have an affect. The next time the keys are typed they take effect. I think must be related to [this here](https://github.com/wbthomason/packer.nvim/blob/f62f2fc1fb1802a217afdbac6a487e541019f658/lua/packer/compile.lua#L133). According to [the docs](https://neovim.io/doc/user/eval.html#feedkeys()) this requires to use double quotes to make the special keys working. But I don't know how to achieve that. The [nvim_feedkeys](https://neovim.io/doc/user/api.html#nvim_feedkeys()) API function allows to specify a parameter to "trigger" the auto-espace of special chars. But it still does not work for me. Does someone has an idea?
=> Fix escaping of keys with <Plug> for lazy loading

lua/packer/compile.lua
I'm very sorry, but during the requested name changing of the variables from `func` to `fn` I forgot an occurrence (because it was a plain string) and another I adopted wrongly. 
Furthermore while using this new feature I discovered that autoload functions appear not to work. The `FuncUndefined` event does not get emitted for these. I hope that it is only a matter of escaping the `#` character and not a completely special treatment of autoload functions. I'll open a new PR for such a feature extension (if you wanna call it like that).
=> Fix typos for lazy loading via functions

lua/packer/compile.lua
This PR fixes the handling of the `keys` option.
- The `<` and `>` characters are escaped to prevent keycodes from being expanded. Fixes #147
- The `\` character is escaped to avoid accidentally expanding special characters. For example, `"\f"` expands to a formfeed in `expr-quote`s, when the user probably wants the literal characters "backslash f". Fixes #155
- The `"` can technically be used in a mapping, so I decided to escape it as well.
I've also decided to use `nvim_replace_termcodes()` instead of handling `<CR>` and `<Plug>` manually (I realize this was changed very recently in #153, sorry about that)
I made a very simple test plugin locally to ensure everything was working correctly:
<details>
<summary>plugins.lua</summary>
```lua
local packer = require('packer') …
```
=> Escape problematic characters when lazy-loading mappings

lua/packer/compile.lua
As suggested by @akinsho in #161, wrap `packer_load` in `pcall` to report errors with a little more context.
@akinsho: Is this what you had in mind? I suppose we might also want to wrap the entire script in a vimscript `try...catch` too.
=> Wrap packer_load with pcall

lua/packer.lua
This PR will fix #152 by automagically reloading any required configs in the packer startup call when compile is called.
@wbthomason this largely works as discussed except for one big caveat which is that the file where the user's plugins are specified needs to be reloaded (using luafile) before the change is picked up. From what I can tell the `precompile` (can change any names or relocate any functions) function correctly reloads the module but `compile` doesn't seem to actually rerun once packer is started up already i.e. it doesn't seem able to pick up any changes itself.
You can't see my key presses unfortunately (don't have any good software for that), but I run packer compile then switch window
~I tried reloading the module where the user called `packer.startup` using …
=> Reload required config/setup modules before packer compile

lua/packer/clean.lua
This relates a bit to #56. I read through that issue and so I'm hoping I didn't misunderstand how this is intended to work. @wbthomason mentions in that issue that `disable` should work similarly to a conditional i.e. if a plugin is disabled it should be removed and the declaration ignored generally as though it is in an if statement.
If plugins are disabled they are picked up for cleaning *which is correct* as far as I understand. They are cleaned i.e. removed from the system. *Now for the problem*, __subsequent calls to PackerClean still try to remove these plugins__ even though they are no longer installed.
`PackerClean` should not offer to remove things that do not exist on the system.
If you look carefully at this screen shot you will see that packer is offering to clean plugins that …
=> Only try and remove disabled plugins that are installed

README.md, doc/packer.txt, lua/packer/compile.lua
This PR will fix #167 by exposing the packer plugins table as a `lua` global as `packer_plugins`. I chose to prefix it since `plugins` as a global seemed way too likely to clash with something.
A user can now do
```lua
if packer_plugins['coc.nvim'] and packer_plugins['coc.nvim'].loaded then
print('Coc is Loaded!')
end
```
@wbthomason was this what you had in mind? 
Changes:
* Rename `plugins` -> `packer_plugins` I explictly used `_G` in the definition so it's clearer that this is intentional.
* If a plugin is `not opt` I set it's loaded value to true
I tested this locally and nothing *seemed* to be broken but would appreciate a second pair of eyes
Also this seems like it should be clearly documented somewhere but I don't know where. `vim-plug` has a wiki for these sort of tips and tricks, …
=> Expose packer plugins table

README.md, lua/packer.lua
This is a follow up to #158, now that required configs and setups are reloaded when packer compile is run, this pr adds a config-gated way to also automatically re-source the `packer_compiled.vim`. The config key I chose is `auto_reload_compiled` and defaults to `true` but I'm happy to change either.
I defaulted to `true` since I think/hope the vast majority of users have simple enough configs and they'd automatically get the benefit of things reloading without having to discover this option first and this could be an opt out for people with complex configs.
NOTE: this doesn't work with plugins that seem to be optional or lazy loaded, I haven't dug into the full compiled output but I'm guessing those plugins setups etc are skipped till they are loaded which is expected but also means that …
=> Auto reload packer compiled on compile

lua/packer.lua, lua/packer/display.lua, lua/packer/plugin_types/git.lua
This PR adds the ability to view a diff of plugin changes when they are updated. It is similar to the `PlugDiff` command from `vim-plug`. So a user can see what bits of the code were changed. Fixes #78
=> Add plugin update diff preview

lua/packer.lua, lua/packer/display.lua, lua/packer/plugin_types/git.lua
This PR fixes a bug/enhances the changes in #183. Currently the `diff` command will show the first revision in the plugin's revisions which doesn't actually map to the changes shown for the update. This PR makes this functionality work exactly like the `PlugDiff` command in `vim-plug` i.e. hitting `d` on a given line show the diff *for that commit* as well as the commit message in full
=> Diff command should show commit for the given line

lua/packer/compile.lua
The changes introduced in e1aa188c2bf61c9a791df7fc3ccd3e59b946f3ce caused a few regressions:
- The `prefix` key for lazy-loading keymaps still used the syntax for Vim dictionaries
- Since the code now uses Lua strings, the `"\<"` and `"\>"` escape sequences are invalid. `<` characters have to be replaced with `<lt>`
Let me know if you have comments/concerns!
=> Various fixes related to keymap lazy-loading

lua/packer.lua
This is a followup to #144. We discussed that `:PackerInstall` and `:PackerUpdate` needed to clean before peforming their operations, since directory changes may have occurred. In order to prevent an increase to the complexity of `:PackerSync`, this PR implements changes to the high-level Vim commands `:PackerInstall` and `:PackerUpdate` in order to perform the clean.
* This means that `packer.install()` and `packer.update()` do not clean automatically, but their respective commands do.
I'm happy to discuss this solution as well as potential alternatives.
=> ref: clean before :PackerInstall/Update

lua/packer/compile.lua
Since all the `loadstring` constructions now use the same behavior, it can be
factored out into a function `make_try_loadstring`.
Cf. https://gitter.im/neovim/neovim?at=60216957063b6c68d54909f4 and
https://gitter.im/packer-nvim/community?at=6021a6a50eed905f189ed6f0
=> Fix: Use try_loadstring in plugin config

README.md, lua/packer.lua, lua/packer/luarocks.lua
This PR will hopefully eventually add argument keys to `use_rocks` to be passed on to luarocks during installation.
There are currently a few bugs/kinks to work out/ a potentially breaking change for any early adopters.
Currently the API for specifying luarocks allows specifying the version of a rock as
```lua
use_rocks {"cjson", "2.1.0"}
user_rocks {"cjson", "penlight"}
```
I might have misunderstood the intended patterns for usage but the above 2 patterns are in conflict short of using a regex or something to detect that one of the two patterns includes a version number.
@wbthomason would appreciate some input on how this API should work, in this PR I've tested moving the version specification to an explicit key, since it makes things clearer and allows listing strings to work since it …
=> Add arguments to luarocks installation

lua/packer/compile.lua
When there are multiple plugins defined with `rtp`, the compiler was concatenating the path strings directly. This is a simple fix to add the string concatenation operator.
=> Fix compilation when there are multple rtp settings

README.md, lua/packer/luarocks.lua
@wbthomason, this resolves the issue raised in gitter and discussed in #187. It allows specifying an `env` key for `luarocks` so you can pass arguments such as `OPENSSL_DIR` for the `openssl` rock, as an example.
```lua
use_rocks {"openssl", env = {OPENSSL_DIR = "<value>"}}
```
@clason could you try this branch out and see if it does what you need.
=> Allow env key and more luarocks arguments

README.md, doc/packer.txt, lua/packer.lua, lua/packer/compile.lua
This PR borrows heavily from dein's implementation of `on_lua` to lazy load a vim package if its lua module is required e.g. 
```lua
-- somewhere in init.lua
use {'akinsho/nvim-bufferline', module = 'bufferline'}
require('bufferline').setup{}
```
Will fix #108
=> Lazy load package on require

README.md, doc/packer.txt, lua/packer.lua
This feature can enable automations that require knowing when an
asynchronous Packer operation completes. For example, to automatically
sync and quit nvim, you can do something like this:
```viml
function! SyncPluginsAndQuit()
autocmd User PackerComplete qa
PackerSync
endfunction
```
=> Implement User autocmds

README.md
@wbthomason this PR adds a small note about `packer_plugins` not being available till after `packer_compiled` is loaded since this I think has come up a few times e.g. #262
=> Add note about usage of packer_plugins table

lua/packer/compile.lua, lua/packer/load.lua
Attempts to close: #250
I have now run multiple times into this issue and it bothers me. While this topic seems to be controversial I decided to give it a try and share my first simple (and working) version here.
Next to the description in the issue, the commit message also includes a kinda generic description of the issue to solve. I settled on the new configuration option name `wants` as a reference to the naming of Systemd service units. So it is not out of nowhere (hopefully many users are already used to it/know its usage) and it also makes sense from the wording to me.
What do you think about the solution? It is pretty simple and flat. I saw some special stuff around (which I have missed since touching the code last time), but it did not look like I need that. Do I miss some …
=> An attempt to resolve lazy loading requirements of plugins

lua/packer.lua, lua/packer/display.lua
<details>
</details>
This PR will provide a new `PackerStatus` function which will open a window listing the currently installed packer plugins and their loaded status. I plan to start minimally by just adding the window with some basic info in this PR but hopefully I can iterate on this window so users can see the most recent commits as well as carry out actions like delete,revert etc. through the UI
This PR will fix #12
- view latest update
- ability to revert
- ability to delete
- ability to load
=> Feature: add packer status

lua/packer/compile.lua, lua/packer/util.lua
This PR fixes an issue where the plugin's install path was being directly concatenated with the `rtp` path rather than joining the two with a path separator as is being done for the actual `&rtp`.
Note for some reason the plugin that was mentioned in #274, `himalaya` still does not appear to load so it's not clear if this is an issue with that plugin or with packer.
Also note (unrelated fix): I took the liberty of fixing a global function I noticed with a very generic name that felt highly likely to eventually cause a clash with some user defined functionality. `restore_cursor`, I think going forward all global callbacks should probably be name spaced under an object like `__packer.callback` to reduce the likely hood of clashes
Fixes #274
=> Fix incorrect rtp directory concatenation

lua/packer/compile.lua
This PR builds on #248 which at present doesn't actually work for a few reasons.
1. The name of the module passed in is not escaped and can contain special characters for lua patterns such as `-`, `.` etc. so the match actually fails in most cases.
2. With the names escaped packages are still not lazy loaded immediately because our loader is second in the list and seems the first loader failing will end up throwing an error.
3. With our loader as first in the list you get an infinite loop error because `require('lazy-load')` will go on cause a bunch of other requires so we need to cache what we have already checked.
@wbthomason this implementation is much closer to [`dein`'s](https://github.com/Shougo/dein.vim/commit/c6ddf04183606413870a0f8a86f61f8d58f85982) which I now believe was the …
=> Fix lazy loading plugins via require

README.md
Passing a List to `system()` saves users the trouble of escaping spaces and other problematic characters
(You can test this with `:call system(['git', 'clone', 'https://github.com/wbthomason/packer.nvim', 'my folder with spaces'])`)
Partially addresses #287
=> docs: Use `system()` in the bootstrapping snippet

lua/packer/compile.lua, lua/packer/load.lua
Previously, we set a plugin as `loaded = true` at the *end* of its part of the load function. However, with the addition of Lua module lazy-loading, the load function is re-entrant. This means that we try to load a plugin in the middle of loading it, which breaks all sorts of things.
These changes move the `loaded = true` mark earlier to prevent this, and include miscellaneous fixes and refactorings for the module lazy-loader.
This does **not** fix the part of #299 that arises from transitive optness with `require`'d plugins; that's a duplicate of #87 and will be fixed in another PR (hopefully in the next few days, if I can get to it).
@shadmansaleh, can you please confirm that this solves #299 for you if you ensure that `plenary` and `popup` are not `opt` first (or wait until the second …
=> Fix first half of #299: Correct module load ordering

README.md, doc/packer.txt, lua/packer.lua, lua/packer/compile.lua, lua/packer/display.lua
This PR adds timing code wrapping each "chunk" of the compiled output, which runs iff the environment variable PACKER_PROFILE is present and true. This allows a simple output of timing information for each part of the compiled loaders.
This is still WIP. The main things it needs are:
- ~[ ] Concatenate output to compiled file~
Pinging @akinsho re: discussion on #191.
=> Feature: autogenerate profiling code for packer_compiled

README.md, doc/packer.txt
I noticed that the `diff` keybinding isn't listed in the README and vimdoc so I added it
=> docs: Add diff keybinding

lua/packer/compile.lua
Attempts to fix #273 by escaping backslashes in event patterns. I'm not 100% convinced that this simple fix won't break something with patterns, e.g. by escaping already-escaped backslashes, but I haven't put together a counterexample yet.
=> Fix #273: Escape any backslashes in event pattern strings

lua/packer/plugin_utils.lua
`vim.g.loaded_remote_plugins = 1` make `Vim:E492: Not an editor command: silent UpdateRemotePlugins`
solved by conditional validation
=> fix(plugin_utils): UpdateRemotePlugins is complaining

lua/packer/util.lua
This was raised in https://github.com/wbthomason/packer.nvim/pull/325#issuecomment-832874005 that an unexpected argument is passed to `util.float` when used as the `open_fn` for packer's display. This PR fixes this issue by checking the `opts` args type before trying to use it in the deep extend function
=> Fix incorrect argument passed to util.float

lua/packer/display.lua
=> fix(display): setf should after content is loaded

lua/packer/display.lua
AFAIK, pclose usually used outside preview window.
Buffer map q to pclose is not necessary when we're inside preview window.
And it doesn't work when move preview window to new tabpage by `<C-w>T`.
=> fix(display): use `close` instead of `pclose`

lua/packer/jobs.lua, lua/packer/plugin_utils.lua, tests/packer_plugin_utils_spec.lua
This PR changes how `packer` handles the current directory for post-update hooks by using the `cwd` option rather than `cd`-ing into the directory
This is mainly for compatibility across platforms since not all shells support the `&&` operator (IIRC older versions of `fish` didn't).
(Note: it might be useful to investigate the `'shell'` and `'shellcmdflag'` options to make this even more portable)
About the test:
It was not obvious to me how to test an async function, so I ended up leveraging `plenary`'s async test functions. That means I'm using `packer`'s `await()` function inside a `plenary` `Future`. Now, this works (probably because both are sugar over coroutines with similar APIs), but it might be too much of a hack for your taste
@akinsho I'd be curious to know whether this PR …
=> refactor(plugin_utils): use `cwd` instead of `cd` 

lua/packer/display.lua
According to docs `\@<=` is really inefficient and recommends using `\\zs` instead of it . 
```
\@<=	Matches with zero width if the preceding atom matches just before what
follows. |/zero-width|
Like "(?<=pattern)" in Perl, but Vim allows non-fixed-width patterns.
Example			matches ~
\(an\_s\+\)\@<=file	"file" after "an" and white space or an
end-of-line
For speed it's often much better to avoid this multi.  Try using "\zs"
instead |/\zs|.  To match the same as the above example:
an\_s\+\zsfile
At least set a limit for the look-behind, see below.
"\@<=" and "\@<!" check for matches just before what follows.
Theoretically these matches could start anywhere before this position.
But to limit the time needed, only the line where what follows matches
is searched, and one line before that (if …
```
=> Fix highlight being disabled due to redrawtimeout

lua/packer.lua, lua/packer/clean.lua, lua/packer/plugin_types/git.lua, lua/packer/plugin_utils.lua, tests/helpers.lua, tests/packer_plugin_utils_spec.lua, tests/plugin_utils_spec.lua
This PR adds in an async check whilst cleaning,updating, and installing plugins i.e. places where the `find_missing_plugins` function was being used, for a git plugins remote url and checks if the repo name from the plugin matches the plugins name in memory, if it doesn't the plugin is marked as missing.
This will fix #231
=> feat: add ability to detect when a different repo with a similar name is added

lua/packer.lua
Fix #375 by wrapping on_complete and adding a missing `await(a.main)`.
=> Fix #375: Schedule slow functions on main thread

lua/packer/plugin_utils.lua
This fixes an unreported error in `packer.find_missing_plugins` which considered uninstalled disabled plugins to be missing. This caused a blank installation window to open on `PackerInstall` if the only missing plugins were disabled.
=> Fix: don't consider disabled plugins missing

lua/packer/plugin_utils.lua
Fixes the bug @uyha reported in the comments of #378, by normalizing the separators in plugin names to match URL separators (i.e. always use `/` instead of Windows' `\`).
@uyha, could you please confirm that this solves the problem? I think it will, but I don't have access to a Windows testing environment, so I'm unsure.
=> Fix #378: Normalize separator direction in detecting plugin repo changes

lua/packer/compile.lua
Currently if a error occurs while running config for a startup plugin. Packer panics and doesn't load any other plugin, neither does create lazy loading bindings . This patch changes that . With this packer will show an error message for failure and go on with usual business .
There's no point in throwing an error when call to `try_loadstring` is unprotected . Instead error message can be displayed with `nvim_echo` and error is gracefully handled inside `try_loadstring`. Also in my opinion `try` should mean it anticipates an error and handles it without causing a new one :P
I found current behavior really annoying especially when experimenting with plugins . As an error in one plugin just takes down the entire setup .
=> Enhance: don't panic on config error at startup

lua/packer/compile.lua
On Windows the `vim.fn.escape` function was not escaping `\` path
characters leaving invalid escape characters in the `ftdetect` section
of the compiled vim file.
This change adds the windows path character as a character to escape.
Fixes: #396
=> fix: Ignore escape characters in `timed_chunk` compile sections

README.md, doc/packer.txt, lua/packer/plugin_types/local.lua, tests/local_plugin_spec.lua
This PR replaces the use of external programs to create symlinks with the built-in `vim.loop.fs_symlink()` and adds a test for local plugins
EDIT: I've verified that this works on Windows 8.1 while running neovim-qt as administrator. I'm actually unsure whether developer mode on Windows 10 allows all programs to create symlinks or just `mklink`.
EDIT2: Apparently `libuv` calls the `CreateSymbolicLink` API with the `SYMBOLIC_LINK_FLAG_ALLOW_UNPRIVILEGED_CREATE` flag so this should work in theory, but I don't have a copy of Windows 10 to test this with
=> refactor(local): use libuv to create symlinks

README.md, doc/packer.txt, lua/packer/plugin_utils.lua
Fix #355: Allow for `plugin.run` to be a table containing a mix of functions, strings, etc.
=> Feature: allow run key to be a table of mixed types of hook

lua/packer/compile.lua
It is an issue for me from time to time when I update vimrc and failed to compile. Sometimes the error message is obvious and sometimes not.
This PR is to address the case when dependency(after) was not setup up correctly and compile.lua failed of nil dereference.
=> compile.lua: better error messages when nil

README.md
14531 temporarily reverted the behaviour of `nvim_open_win` for a few hours until `noautocmd` was merged in 14659, which caused some confusion upstream. :smile:
=> fix(README.md): refer to the correct noautocmd PR

lua/packer.lua, lua/packer/clean.lua, lua/packer/log.lua, lua/packer/luarocks.lua, lua/packer/plugin_utils.lua, lua/packer/update.lua, lua/packer/util.lua, tests/plugin_utils_spec.lua
This refactoring primarily (1) refactors the main management operations to only read the state of the filesystem (e.g. look for installed/missing plugins) **once** and (2) adds finer-grained debug logging.
These changes are in response to the unusually high "time to display" that @cloggier mentioned on Gitter; for me, this version reduces the average time to display from 0.3s to 0.15s.
This PR also contains some minor renaming/reformatting.
=> Refactor: faster operation startup

README.md, doc/packer.txt, lua/packer.lua, lua/packer/plugin_utils.lua
Closes #433. Introduces a new config variable, `config.git.default_url_format` which is a format string used in `plugin_utils` if a plugin is specified in the `aaa/bbb` form rather than with a full local path or URL. Allows users to customize the default source/URL pattern for plugins, as described in #433.
@jdhao, can you take a look and make sure this does what you wanted?
=> Add config.git.default_url_format to allow customizing default URLs

README.md, doc/packer.txt, lua/packer.lua, lua/packer/clean.lua, lua/packer/plugin_types/git.lua
This PR:
- changes the default `git.install` command and how `git.setup()` handles URLs/paths for that command
- uses `vim.fn.delete()` to remove dirty plugins instead of `os.execute()` (as a bonus, this removes the last reference to `is_windows` outside of `util.lua`)
Together with #303, this should address #165 and #287.
The issue with the current approach is that `run_job()` [uses whitespace to split strings](https://github.com/wbthomason/packer.nvim/blob/b76bfba54031ad28f17e98ef555e99cf450d6cb3/lua/packer/jobs.lua#L173-L176), which means any path that contains whitespace will make the command fail.
This PR changes the API so that `git.install` can be split early before inserting the paths in the newly created table with `table.insert()`
=> fix!: insert paths separately to avoid splitting

.github/workflows/formatting.yaml
@wbthomason this adds a github workflow for stylua.
A few things to note:
* It's currently set to format whenever anything is added to the `master` branch, I had t this way on my projects just to make sure nothing got missed, but it could alternatively be on PRs.
* The author of the formatting commit is the github bot, I've done it this way as I just saw a bunch of examples and copied them, I personally don't care much, but it could be changed
* I've ignored doc files like `.md`
I haven't actually formatted the repo as part of this change
=> ci: add workflow for stylua formatting

lua/packer/compile.lua
After the recent PR, error messages occurring in the `packer_compiled.lua` file (such as in configs, or plugins) were left blank. This was my bad— `pcall()` raises its own errors, and they don't interfere with `v:exception`.
=> fix(compile): blank `packer_compile` error messages

lua/packer.lua
This fixes an issue where if a top level spec for a plugin was called
after a required spec for that, a duplicate error was shown.
e.g.
```lua
use {'first/plugin', requires = {'another/plugin'}}
use 'another/plugin' -- <- This would throw a duplicate plugin error
```
This PR instead adds a flag to ignore the duplicate warning if the initial
plugin spec was from a `require`.
This is based off of https://github.com/wbthomason/packer.nvim/issues/258#issuecomment-876568439.
=> Allow top level and required plugin usages

lua/packer/compile.lua
This was a fun one! #469 was caused because the `module` lazy-loader had the following control flow:
1. Call `packer.load` for the plugins that needed to be loaded
2. In `packer.load`, run any `config` key functions, **which may require the lazy-loaded module**
3. Return `nil`, to pass on the loading process to a subsequent module loader
The problem is that, in step 2, the lazy-loader may get recursively invoked but (correctly) skip to step 3, actually loading the module. Then, by doing step 3 **again** in the original invocation, we basically force the package.path/other loader to run again, re-loading the module.
This commit fixes the issue by instead returning the **already loaded** module from `package.loaded`, if indeed this value exists.
Closes #469
=> Fix #469: Avoid re-running module loaders for lazy-loaded modules

lua/packer/compile.lua
vim.fn.exist(':Bar') return 1 if `BarBar` has defined, should use full match instead
The below snippet is produced by packer.nvim, and I add some comments for debugging.
```lua
-- Command lazy-loads
time([[Defining lazy-load commands]], true)
if vim.fn.exists(":GitMessenger") == 0 then
vim.cmd [[command! -nargs=* -range -bang -complete=file GitMessenger lua require("packer.load")({'git-messenger.vim'}, { cmd = "GitMessenger", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, _G.packer_plugins)]]
end
-- add by kevin
-- print('exists? :', vim.fn.exists(":Git"))
if vim.fn.exists(":Git") == 0 then
vim.cmd [[command! -nargs=* -range -bang -complete=file Git lua require("packer.load")({'vim-fugitive'}, { cmd = "Git", l1 = <line1>, l2 = <line2>, bang = <q-bang>, args = <q-args> }, …
```
=> fix(compile): should check command strictly

README.md, doc/packer.txt, lua/packer/compile.lua
Closes #478 by adding a new key, `module_pattern`, which works exactly the same as `module` but does not run `pesc` or prepend a caret to the pattern.
@thezealousfool: Can you please confirm that this does what you wanted in #478?
@akinsho: If you have a chance to try this out, that would be great, but as always nw if you don't have time, etc.
=> Add the module_pattern key

README.md, lua/packer.lua, lua/packer/display.lua, lua/packer/plugin_types/git.lua
This is a slapdash implementation of the idea @sunjon, @clason, and others proposed on Gitter. It looks at commit headers and bodies for an update and, if it finds the strings "breaking change" or "breaking_change" (case insensitive), marks the commit as potentially breaking, emitting a warning log message and highlighting the commit hash in the status window.
=> Feature: add very simple breaking change detection and marking

README.md, doc/packer.txt, lua/packer/compile.lua
Fixes #408
The downside to this is that command autocompletion no longer works.
Potentially the old way could be a seperate option?
=> Use CmdUndefined autocommand for lazy loading on commands.

lua/packer/compile.lua
nvim-0.5 has supported sourcing lua files, including `so *.lua` cmd.
=> feat(compile): support lua files in after directory

README.md
Applying the earlier example verbatim without thinking about it would lead to the autocommand being re-created each time plugins.lua was reloaded, and could make PackerCompile "feel slow" because it was run multiple times.
=> Wrap the example PackerCompile autocmd in an augroup

lua/packer/plugin_utils.lua
Fix #551 
The default value of `vim.o.shell` on Windows is `cmd.exe` or `C:\WINDOWS\system32\cmd.exe`, and `cmd` shell rejects the parameter `-c`, use `/c` instead when the shell is `cmd`.
By the way, you can not just check the OS since the `powershell` on Windows should use `-c` parameter.
=> Fix #551: failing to run command post hooks on Windows

lua/packer/plugin_types/git.lua
Fixes #558 by adding a fetch before handling checkouts for git plugin updates. In my testing, this allowed switching between specific (and previously unused) branches and commits, as well as the "default" HEAD specification.
@stasjok @JoseConseco can you please confirm that this fixes the issue for you?
=> Fix: Fetch before checkout on git update

lua/packer/compile.lua
Attempt to partially address #272 . @wbthomason you mentioned that `cond` plugins should use the load mechanism so the sequencing logic could be taken advantage of. I'm not sure whether just using `packer.load` is enough though since in a very brief test doing this seems to cause the `cond` plugin to load as expected but the `after` plugins do not
=> fix: use packer.load for plugins loaded via cond

lua/packer/display.lua
Plugins appearing at random positions in `PackerStatus` is just annoying
=> enhance: sort lines in PackerStatus

lua/packer/plugin_utils.lua
This PR fixes #566 by not prematurely returning after the first hook runs. Now, we return either
after the first failed hook (to prevent a long chain of failures) or after all hooks have
successfully run.
=> Fix #566: Run all post install/update hooks

lua/packer/display.lua
After #658, we display plugin URLs in the status window after an update. Unfortunately, this broke the simple heuristic used for finding the nearest plugin name to determine which set of info to toggle, because plugin names now appear in two places. This PR fixes that bug by checking for the ' URL:' prefix to a line, and additionally fixes a minor bug wherein we were not restoring cursor position after toggling.
@n3wborn: Can you please confirm that this closes #681 for you?
=> Fix: Don't duplicate URL in plugin info display on toggle

lua/packer/compile.lua
This PR fixes #714 by adding the `simple_load` condition to mark plugins which don't use any features and are just directly loaded. This works around an edge case wherein a plugin loaded `after` such a simply-loaded plugin would not be correctly added to the sequenced loads and therefore would not be loaded.
=> Fix #714: Add sequencing constraints for simply-loaded predecessors

README.md, doc/packer.txt, lua/packer.lua
Fixes an oversight wherein there was no way to add rocks separate from a plugin (i.e. the `use_rocks` style) if you use the table-only form of `packer.startup`.
=> Feature: Add option to specify use_rocks-style Luarocks in the table form of startup

lua/packer/plugin_types/git.lua, lua/packer/update.lua
If a git repo is not reachable a nil exception is thrown (neovim v7 nightly)
These small changes handle this scenario without crashing out.
=> Handle unreachable git repos without nil exception

lua/packer.lua, lua/packer/display.lua
I added a config to hold the item symbol use to list the plugins. I also improve `find_nearest_plugin` so it only returns line that contains a valid plugin item. This fixes the collapsing and expanding of plugin item in the plugins buffer.
=> Fix find_nearest_plugin in display buffer

lua/packer.lua, lua/packer/plugin_types/git.lua
Hello, 
Providing support for wildcards, as discussed in #529, in the effort of providing plugin managers ways to follow plugin versioning.
For example, if the plugin has these tags:
```
1.0.0
0.1.0
0.0.11
0.0.10
```
And you add `tag = "0.0.*"`, it'll follow `0.0.11`. Doing `tag = "*"` will follow latest tag. 
If the wildcard expansion did not succeed, will default to latest commit with a warning log.
Some TODO:
=> Tag Wildcards support

lua/packer.lua
Fix #802 by using the correct path separator (rather than assuming that it's the same as the FS path separator) in separating a plugin's name segments.
=> Fix #802: Use correct path separator in finding plugin name

lua/packer.lua
Somewhat trivial case, but I run `packer.compile` at startup and wish I could turn off the notification. Thanks for all your hard work!
=> feat: add option for quiet compilation

vim.toml
"jit" is used by packer/luarocks.lua
=> Add "jit" to valid variables that selene understands.

lua/packer/luarocks.lua
If package name contains any uppercase chars, PackerUpdate action always displays `✓ Installed packerName`.
reference:
- https://github.com/luarocks/luarocks/blob/8f3ce333e7a1abfc6bf0488817d9eff4a2fd443f/src/luarocks/rockspecs.lua#L121
=> fix(luarocks): use lower string as package name

README.md, lua/packer.lua, lua/packer/clean.lua
Automatically removes unused or disabled plugins without asking the user if set to true.
=> feat: add autoremove option

lua/packer.lua, lua/packer/util.lua
I'm preprocessing plugin specs at the moment (until the config merging PR lands) and, in that context, it's sometimes useful to refer to a plugin's canonical short name outside of packer. I figured why not expose the functionality in general?
If you think this isn't necessary, feel free to close this, of course. :)
=> Expose functionality to get a plugin's short name

lua/packer.lua
=> fix: move snapshot configuring to packer.init()

lua/packer/luarocks.lua, tests/helpers.lua
PR #857 introduced a change which prevents the full data from a rock
from being used in its installation, e.g.
```lua
{
"lyaml", server = "http://server", env = {YAML_DIR = "/usr/local"}
}
-- Is changed to
{"lyaml"}
```
Was no longer being passed as each rock was being transformed to just
it's name with not metadata passed on during the case change
@kevinhwang91 can you please check if your usecase is still satisfied with the change in case of the rocks. If so I'll merge this unless @wbthomason steps in
=> fix(luarocks): rock metadata not passed in install

README.md
adds the variable `use` in quickstart
lsp errors show up when this is not specified
=> add `use` in quickstart

README.md
Opening Neovim for the first time trying to bootstrap packer would fail because packer wouldn't be loaded until the second time Neovim was opened.
Added the `packadd` command to correct this issue.
=> Add packadd command to load packer when bootstrapping

lua/packer/util.lua
In some cases, there could be the need to activate the "shellslash" option on windows. In the current version of packer.nvim, this would create problems when installing new modules or doing a sync of the installed ones. It would not load any module after doing a sync. This is related to #911
I've added a check so that packer.nvim is able to handle the shellslash option. Tested locally by doing the "install" steps in the readme, and it worked flawlessly, I hope it could be of some help to others too.
Let me know what you think 🙂
=> Fixed shallslash issue on Windows

lua/packer/compile.lua
After running `PackerCompile`, plugins specified in `after` key would miss some fields in the generated `packer_compiled.lua` file, for example, let `nvim-notify` be loaded after `telescope.nvim`:
```lua
...
use {
'nvim-telescope/telescope.nvim',
config = function()
require('young.mod.telescope').done()
end,
}
use {
'rcarriga/nvim-notify',
after = 'telescope.nvim',
}
...
```
and in the generated `packer_compiled.lua` file, loader for `telescope.nvim` would missing fields like `config`, `url` and `path` :
```lua
_G.packer_plugins = {
["telescope.nvim"] = {
after = { "nvim-notify" },
loaded = true,
only_config = true
},
}
```
After this fix, it would be normal:
```lua
_G.packer_plugins = {
["telescope.nvim"] = {
after = { "nvim-notify" },
config = { …
```
=> fix(compile): avoid overriding fields of plugins specified in 'after' key

lua/packer.lua
This change ensures that `output_path` doesn't get transformed into "" if `packer_compiled.lua` is in `&wildignore`.
=> Add `nosuf = true` param to `vim.fn.expand()` call

lua/packer.lua
A quick fix to this issue. Push using require_and_configure for 'log' in packer.startup to after loading config, so that log level is respected.
This means requiring 'log' twice though - there might be a better way...
=> Fix #704: respect log level config

lua/packer/plugin_types/git.lua
This PR will add the ability to recognize these pretty common formats:
- `type!: body`
- `type(scope)!: body`
=> feat: treat "type!:" pattern as a breaking change

lua/packer.lua, lua/packer/util.lua
Removes `.git` from url only if it ends with `.git`.
Resolves: #1022
=> fix(git): remove `.git` from end url only

lua/packer/util.lua
Correct Lua pattern from #1023, resolves https://github.com/axieax/urlview.nvim/issues/32
=> fix(git): correct `.git` pattern from end url

lua/packer/util.lua
@akinsho apologies but it seems like there's still a dangling period character left behind from the previous commits. This should hopefully address it!
=> fix(git): use vim.endswith to check git suffix

lua/packer.lua, lua/packer/display.lua, lua/packer/plugin_types/git.lua
If there is a range of commits, eg `00cba85..116a568` then the diff no longer only shows the diff of the first commit but of the whole range. Currently this shows the diff for each commit and not the total diff from the first to the last but that can be configured by the user with a different command.
@akinsho, I think you initially implemented this so maybe you'd be interested and I'm happy to hear any thoughts.
=> feat(git): support showing diff of range of commits

lua/packer.lua, lua/packer/display.lua
This allows to opt-in for having all the infos closed by defaults in the final update results. They can still be opened as normal with `<CR>`.
=> feat(display): allow not showing info by default when displaying results

lua/packer.lua
Should fix #1038 by adding a missing check for a possible `requires` case.
@glepnir, does this work for you?
=> Fix: check if a plugin given as a requirement is a single-specification table

lua/packer/plugin_types/local.lua, lua/packer/util.lua
If a local plugin is installed and then the path is moved this was not
checked for in the local update function. This change checks if the
current dest link points to the desired src. If not then the link is
re-created.
Resolves: #944
=> fix(update): Validate local symlinks on update

README.md
Fixes bootstrap code in README.md which erroneously tries to clean the newly installed packer.nvim package when there are no packages listed in the `startup()` call.
Fixes #742
=> fix: README bootstrap error (fixes #742)

lua/packer.lua, lua/packer/log.lua, lua/packer/snapshot.lua
`vim.notify` exists now, and is preferable to the old `echom` method of logging. Some parts of `packer` used `vim.notify` directly, while some used `log`. This led to inconsistent output.
This PR makes the `log` API use `vim.notify` internally, and moves manual uses of `vim.notify` to use the `log` API.
- Use vim.notify instead of echom to log to console
- Move manual uses of vim.notify to use the log API
=> Fix: use vim.notify in packer.log

lua/packer/plugin_types/local.lua
This PR (hopefully - needs testing) fixes #1048 by consistently using `fs_realpath` to resolve local plugin targets at both install and update time.
=> Always fully resolve symlinks

lua/packer.lua, lua/packer/update.lua
Currently if you do eg `PackerUpdate foobar` and there is no plugin `foobar` you get a bit cryptic error about accessing a `nil` value. This just adds a more clear error message.
=> fix(update): error message when unknown plugin is provided

README.md
Notices about year-old bugs or other historical details are not a great intro text. Best to hide that at the end (or remove it entirely).
Similarly, let's minimize the emphasis on Neovim 0.5 min version; it's not new, and no one is running anything older at this point.
Similarly, remove old "current work in progress" status message which is impossible to keep fresh.
Probably more cleanup is warranted, but this is what struck my new-user eyes.
=> README.md: Don't scare reader with crufty notices

README.md
User `9mm` has changed their username on github to `rstacruz` which means the line `use '9mm/vim-closer'` in quickstart will throw an error as `github.com/9mm/vim-closer` no longer exists.
=> README.md: update plugin author username

README.md, doc/packer.txt
Hello,
I would like to propose a small change in the documentation because I was initially confuse on how `setup` worked.
I initially understood it as a function that was ran just before the plugin is loaded, thus only if other conditions such as ft are met.
However, it is really ran unconditionally, so I tried to make that clearer in the documentation and the README.
English is not my native language, so the sentence may still need improvement.
=> Clarification on the behavior of setup.

README.md
Added a missing `--` before a comment. This has been annoying me for a long time.
(The `string/list` in line 400 should probably also be turned into a `string or list`, but that would break the indent of the comment cascade..)
=> Readme: fix code syntax in src block

lua/packer.lua, lua/packer/actions.lua, lua/packer/display.lua, lua/packer/fsstate.lua, lua/packer/plugin.lua, teal/packer.tl, teal/packer/actions.tl, teal/packer/display.tl, teal/packer/fsstate.tl, teal/packer/plugin.tl, types/vim.d.tl
- Renamed `spec.opt` to `spec.lazy`
- Added `spec.start`
- Make sure to load plugin dependencies before loading the plugin
- Allow nested dependency specs
- Only allow a plugin to be specified as a table once. This is tracked
with `plugin.simple`.
=> feat: make all plugins opt by default

lua/packer/compile.lua, lua/packer/load.lua
This is a slight performance improvement over the old style of command creation, and moves `packer` toward the modern Neovim APIs
Not immediately merging because I need to track down the Neovim version when `nvim_create_user_command` was released - if it's v0.8.0, I'll want to hold off on this change since the release was quite recent.
I could add logic to test for the function's existence and fall back to the old method if it's not present, and might. But for now, I'd prefer to avoid adding that complexity.
=> feat(compile): use nvim_create_user_command to make lazy-load commands

lua/packer.lua
In `PackerCompile`, packer will rerun config for these loaded plugins after source `packer_compiled.lua`.
But somehow it missed name and plugin_spec, which is not the case of other place using `loadstring` to run config.
=> fix(compile): missing name and plugin_spec when loading config for plugins

README.md, doc/packer.txt, lua/packer.lua, teal/packer.tl
- add `packer.add()` for adding plugins to the managed set
- add `packer.setup()` for overriding default config. Note this is optional and will be automatically called by packer.add()
- deprecate `packer.startup()`
- updated README and docs.
=> feat: rework startup

lua/packer/cli.lua, plugin/packer.lua, teal/packer/cli.tl
- Removed commands:
- `PackerInstall`
- `PackerUpdate`
- `PackerSync`
- `PackerClean`
- `PackerStatus`
- Added command `Packer` with subcommands:
- `install`
- `update`
- `sync`
- `clean`
- `status`
- any other exported functions from the `packer.actions` module.
=> feat!: re-implement cli with subcommands

lua/packer.lua, lua/packer/display.lua
Fixes #1112
Instead of calculating whether the nvim instance is headless at startup and caching that (both in the config.non_interactive flag as well as a local var in the display module), just recalculate whether nvim is interactive whenever it needs to make the decision (when displaying windows or prompting the user).
=> fix(interactive): let interactive mode work for remote clients attached to headless instances

lua/packer/jobs.lua
Not all systems have a `python` executable in their path. In this situation, sync will never complete with the message: "installing hererocks...". This fix will log the situation and callback with an error code.
Issue #886
=> Fix bug where hererocks installation hangs

README.md, doc/packer.txt, lua/packer.lua
Fixes #1100. Ensures packer updates don't fail when upstream force-pushes tags. Reopening #1101, because I've tested the solution proposed here by @antoineco. I think it's the best way forward: https://github.com/wbthomason/packer.nvim/issues/1100#issuecomment-1657036413.
=> fix #1100: force Git fetch during updates

lua/packer/plugin_utils.lua
packer.nvim errors when installing `use { 'ssh://git.company/repo' }`
I've tried `git@git.company/repo`, `https://git.company/repo`, `git://git.company/repo` but one of these urls work with packer or with `git clone`.
ssh, git+ssh, ssh+git are all names for git's ssh protocol. I tested this locally and I'm able to install the package.
https://git.kernel.org/pub/scm/git/git.git/tree/connect.c?id=c05186cc38ca4605bff1f275619d7d0faeaf2fa5
=> Detect git ssh protocols
