wbthomason/packer.nvim

lua/packer.lua
lua/packer/util.lua

@clason: This fixes your example in #3 for me - can you confirm that it also fixes things on your end? Thanks!

Fix #3 by removing use of __index metamethod and deep-extending config

---

README.md
lua/packer.lua

Allow startup() to default to packer.use if no function is passed

---

lua/packer/plugin_types/git.lua

fix: Small typo on vim

---

lua/packer/compile.lua

Fix the issue raised in #58.
@IMOKURI: Does this PR fix your issue? If so, I'll merge it in.

Fix sequence config

---

lua/packer/plugin_types/git.lua

I have managed to reproduce issue #40 (and #42 / #26, possibly?), this PR implements a fix using the `GIT_TERMINAL_PROMPT` environment variable.
I would really appreciate it if people who encounter the issue could test the PR to see if it fixes the problem for them as well

Fix git prompt leading to UI freeze

---

lua/packer/display.lua

Also cleans up the tests for valid win/buf and uses them more consistently.

Fix #106 by adding test for --headless

---

lua/packer/util.lua

Restore cursor position after floating window is closed

---

README.md
lua/packer/util.lua

- Added a secondary os detection when jit is not available
based on package.config

Made packer work without luajit

---

README.md
doc/packer.txt
lua/packer.lua
lua/packer/clean.lua
lua/packer/compile.lua
lua/packer/display.lua
lua/packer/luarocks.lua

This is still very work-in-progress, adapting @tjdevries lovely https://github.com/nvim-lua/plenary.nvim/blob/master/lua/plenary/neorocks/init.lua to work with `packer`'s job and display system (and adding plugin-specific logic).

Luarocks, take 2

---

lua/packer/compile.lua
lua/packer/load.lua

Add a step to manually source files in after/plugin if they exist

---

lua/packer/install.lua

seems like a mistake from search and replace

fix: string.fmt -> string.format

---

README.md
lua/packer/compile.lua

no need to write '*' in event keyword.

auto add * in event

---

README.md
doc/packer.txt

docs: Don't mention patterns in module key (#293)

---

lua/packer/compile.lua

Fixes #312 by special-casing the profiling code generation for conditionals. This is necessary because - unlike for other kinds of timed chunk - we cannot easily put `time` calls around the chunk in the conditional syntax.
@seblj, @yutkat, @yujinyuz: can you confirm that this fixes #312 for you without causing new issues? It works for me on the minimal reproducer. Thanks!

Fix #312: Correctly generate profiling code for conditionals

---

README.md
doc/packer.txt
lua/packer.lua
lua/packer/display.lua

I honestly sometimes have hard time finding this float :P Colorscheme might have a hand in that . But borders are cool and with bfredl making them so easy to add I see no reason not to have them :)

Add border to remove prompt

---

README.md
doc/packer.txt
lua/packer.lua

Packer load command loads the plugins provided in argument
This was really easy everything was already there . Thanks @wbthomason @akinsho 
I still need to add some docs :)
closes #301

Feat: Add PackerLoad command

---

lua/packer/display.lua

This PR closes #359 
I have removed the trailing whitespaces on the display. I have tested it and it seems that everything is in the right place.

Fix extra trailing white spaces

---

lua/packer.lua
lua/packer/clean.lua
lua/packer/plugin_types/git.lua
lua/packer/plugin_utils.lua
tests/helpers.lua
tests/packer_plugin_utils_spec.lua
tests/plugin_utils_spec.lua

This is #340, plus my commits to fix up normalizing plugin URLs and tweak the awaiting of the main thread (it should happen as close as possible to the slow Vim function calls that require it).

Feature: detect repo changes

---

lua/packer/plugin_utils.lua

For plugins specified as full URLs (e.g. usually non-Github plugins), `packer` stores the plugin name as the full URL. #374 introduced a regression where we would only check the final two components of this URL - a Github-style repo name - against the plugin name to determine if the plugin repo has been changed. This causes other plugins to be incorrectly queued for removal.
These changes add a test against the (normalized, to deal with https:// and ssh://git@ prefixes) remote URL and plugin name, queuing a plugin for removal iff both its remote URL and plugin name don't match and the "Github-style" repo name and plugin name don't match.
Fixes #378.

Fix #378: Check that a plugin's remote isn't its name

---

lua/packer/compile.lua
lua/packer/load.lua
lua/packer/plugin_utils.lua

Fix recursive glob on Windows, fix filename escape during load

---

README.md

Create the windows installation command

feat: Add the windows installation command

---

lua/packer/plugin_utils.lua

fix windows error #418

---

lua/packer.lua

This PR is 90% a single variable renaming in `manage`. The important bit is the addition of line info, i.e. the line of a user's plugin specification file at which `use` was called, for reporting errors in plugin specifications (e.g. duplicate aliases).

Report line info for debugging incorrect plugin specifications

---

lua/packer/plugin_types/git.lua

I introduced a regression in #303, sorry about this!

fix(git): put the `cwd` option in the right table

---

README.md

Update suggested autocommand to source plugins.lua

---

lua/packer.lua
lua/packer/compile.lua

This PR adds a check around each lazy-load command creation to only create the lazy-load command if a command with the same name does not already exist.
This should fix issues like https://github.com/kyazdani42/nvim-tree.lua/issues/471 and #442.
@gegoune: If you have a chance, could you please try this with the `nvim-tree` use case you described on Gitter?

Check that a lazy-load command does not already exist before creating it

---

lua/packer/compile.lua

combine pcall and com without ! to avoid define defined commands

perf(compile): optimize the startup time of compile file

---

lua/packer.lua

Fixes #503 by doing what the title says.
@mjlbach: Does this do what you wanted for #503?

Set non_interactive = true if neovim is headless

---

lua/packer/load.lua

Add `syntaxset` group FileType command after adding plugin

---

README.md

This will result in a blazing fast clone speed even on slow 3g networks.

Fix: Add `--depth 1` flag to clone faster

---

doc/packer.txt
lua/packer.lua

- Now :PackerUpdate/Install/Sync can be used to operate on specific plugins
- PackerLoad now uses <f-args>

feat: enable :PackerUpdate/Install/Sync to operate on specific plugins

---

README.md
doc/packer.txt
lua/packer/compile.lua
lua/packer/load.lua

Description in the commit message.
This is workaround for #655 .

Pass name and plugin table to config function inside try_loadstring

---

lua/packer/plugin_types/local.lua

Fixes #679 by implementing a slight variant of the workaround suggested by @nonsleepr.
@nonsleepr, could you please try this PR and confirm that it fixes #679 for you? Thanks!
EDIT: Sorry, @ binx - I think I meant to tag another user, but  their Matrix chat name is not the same as their Github username, and I tagged you accidentally. Sorry for the noise!

Fix local plugin installation on Windows

---

lua/packer/luarocks.lua

latest branch look like deprecated

fix(luarocks): update hererocks url

---

lua/packer/compile.lua

This allows adding a description to a mapping and is based on @matheussampaio diff, I just applied the patch and verified it works locally
fixes #875

feat(compile): allow adding mapping descriptions

---

lua/packer/compile.lua

@konart can you please test this branch to see if it fixes your issue
fixes #988

fix: use escaped mappings for compiled keymaps

---

lua/packer/compile.lua

This reverts the changes to allow adding descriptions for mappings

revert(compile): undo mapping descriptions 

---

lua/packer/plugin_types/git.lua

solves https://github.com/wbthomason/packer.nvim/pull/1034#issuecomment-1234414343

fix(git): empty line between messages

---

lua/packer/compile.lua
lua/packer/load.lua

feat(load) delay BufRead if inside packer_compile

---

README.md

It added a newline at the end but not used a multiline comment :(

Fix wrong format

---

README.md

Some code changes to the bootstrapping code:
- Encapsulates the code required to install packer  
- Avoid variable mutation `packer_bootstrap`
- Solves linter warnings `undeclared packer_bootstrap`

Refactor bootstrapping code

---

README.md
doc/packer.txt

Fixing a small typo in the docs.

docs: fix typo

---

lua/packer.lua
lua/packer/handlers/cmd.lua
lua/packer/handlers/event.lua
lua/packer/handlers/ft.lua
lua/packer/handlers/keys.lua
lua/packer/handlers/util.lua
lua/packer/plugin.lua
teal/packer.tl
teal/packer/handlers/cmd.tl
teal/packer/handlers/event.tl
teal/packer/handlers/ft.tl
teal/packer/handlers/keys.tl
teal/packer/handlers/util.tl
teal/packer/plugin.tl
types/vim/api.d.tl

In light of #1143, I thought I'd take a stab at handling this *properly*.
Not sure if this is good or works as intended.

feat: make sure handlers destruct themselves when plugins are loaded

---

lua/packer/loader.lua
teal/packer/loader.tl
types/vim/uv.d.tl

About 3x faster to traverse the filesystem

feat: use libuv instead of glob()

---

lua/packer.lua

Fixes #1086
@nat-418, @notwidow

Fix: Change display headline text to not indicate that all tasks are plugins
